import type { ThemeConfig } from './types';

export const daggerheartTheme: ThemeConfig = {
  id: 'daggerheart',
  label: 'Daggerheart',
  colors: {
    parchment: '#f3e6c4',
    ink: '#1a1208',
    inkMuted: '#5a4a32',
    gold: '#c9a14a',
    accent: '#c2612f',
    danger: '#a62828',
    cardSurface: 'rgba(243, 230, 196, 0.96)',
    cardBorder: '#5a4a32',
    health: '#e4443a',
    steel: '#7fa0c4',
    hudSurface: 'rgba(22, 15, 7, 0.74)',
    hudSurfaceStrong: 'rgba(14, 9, 4, 0.9)',
    hudBorder: 'rgba(201, 161, 74, 0.55)',
  },
  typography: {
    fontFamilyDisplay: '"Cinzel", "Trajan Pro", "Times New Roman", serif',
    fontFamilyBody: '"Inter", "Helvetica Neue", system-ui, sans-serif',
    fontSizeBase: '24px',
    fontSizeHeading: '40px',
    fontSizeLabel: '19px',
    fontSizeTitle: '72px',
  },
  layout: {
    spacingXs: '4px',
    spacingSm: '8px',
    spacingMd: '16px',
    spacingLg: '24px',
    spacingXl: '40px',
    radiusSm: '4px',
    radiusMd: '10px',
    borderWidth: '2px',
    pipSize: '30px',
    heartSize: '52px',
  },
};
